name: Deploy bk-chat-node

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false

      - name: Build and deploy
        run: bash deploy.sh
